server.port=8081
spring.application.name=ticketguard

# Supabase Database
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?\
  user=postgres.jfdsvhfyfemzuaskaxhv&password=r!ngw0rm200
spring.datasource.username=postgres
spring.datasource.password=r!ngw0rm200
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=TicketGuard2026SuperSecretKeyForHackathonMakeItAtLeast64CharactersLong!!!
jwt.expiration=86400000

# OTP
app.otp.expiry-minutes=5

logging.level.org.springframework.web=INFO
logging.level.com.ticketguard=DEBUG